### ISSUE TITLE
wrong check points

### ISSUE THREAD

**Issue by hongxianglics** [wangyu-sd/MechRetro#1]
Hi,

When I was trying to use your model, I notice that the link you shown for the checkpoints is not a checkpoint but the csv file for commercially available products. I guess this is a wrongly uploaded file and could you please upload the correct checkpoints? Thanks in advance!

Best

**Comment by wangyu-sd** [comment]
Thanks for pointing out that. The wrong URL has been corrected.

**Comment by hongxianglics** [comment]
Hi,

Thanks for your quick response! I tried to download the checkpoints for multisteps and it shows the access is denied. I have sent a request and could please offer the access? Thanks!
<img width="519" alt="捕获" src="https://user-images.githubusercontent.com/104338096/203118613-b7be736c-ee99-4803-92e6-85a31982ca78.PNG">
