### ISSUE TITLE
access denied

### ISSUE THREAD

**Issue by hongxianglics** [wangyu-sd/MechRetro#2]
Hi,

Thanks for your quick response with my previous question! I tried to download the checkpoints for multisteps and it shows the access is denied.(see figure below) I have sent a request and could you please offer the access? Thanks!
<img width="519" alt="捕获" src="https://user-images.githubusercontent.com/104338096/203119172-d4dd13b2-2074-4a5a-b659-c2c962f35d78.PNG">

**Comment by wangyu-sd** [comment]
Hi, thanks for the reminding. We have re-opened this URL.

**Comment by hongxianglics** [comment]
It works! Thanks very much!
