### ISSUE TITLE
ImportError: cannot import name 'MultiStepDataset' from 'data.datasets' 

### ISSUE THREAD

**Issue by hongxianglics** [wangyu-sd/MechRetro#3]
Hi,

When I tried to run the file api_for_multisteps.py, I got the error below.
<img width="732" alt="捕获" src="https://user-images.githubusercontent.com/104338096/203655614-5b5b441d-735a-4902-8eff-2ab4b2fb0fc3.PNG">
 ` File "C:\Users\86130\Desktop\retrosynthesis\MechRetro-main\model\RetroAGT.py", line 32, in <module>
    from data.datasets import MultiStepDataset
ImportError: cannot import name 'MultiStepDataset' from 'data.datasets' `
Could you please help me with it?
Thanks!

**Comment by wangyu-sd** [comment]
Hi, this is most probably caused by the wrong version we commited. We have updated the file `data/datasets.py`. You can solve this issue through the updated file.

**Comment by hongxianglics** [comment]
Thanks a lot for your help! I appreciate it!
