### ISSUE TITLE
is it possible to predict topk routes?

### ISSUE THREAD

**Issue by hongxianglics** [wangyu-sd/MechRetro#5]
Hi Yu,

Again thanks very much for your previous help! I am now able to run your code and get the prediction.

I notice that the multi-step synthesis output is the best route you found for the target molecule. I wonder if it is possible to get a prediction of several routes for one molecule?(aka top k routes) If not, may I ask will you plan for it?

Thanks!

**Comment by wangyu-sd** [comment]
Hi, the pdf version of search tree can be seen at path `data/multi-step/viz/mol_0_search_tree.pdf`.

**Comment by hongxianglics** [comment]
Hi Yu,

Thanks for your help! I found the pdf file with search tree and I also went through the python file `mol_tree.py` and other python files under `retro_star\retro_star\alg` file folder. If I understand this correct, each branch in the search tree represent a synthesis route and the chemicals in yellow color means the compound is commercially available and thus the route is "finished".

Here I have two questions:

First, is it possible to extract all the "finished" routes as an output list other than the pdf file.(Suggesting me to read specific parts or file in your model will also help!)

Next, can I get a rank or score of those "finished" routes in your model?  
Thanks in advance!

Best,

Hongxiang

**Comment by wangyu-sd** [comment]
Hi Hongxiang,

Thanks for the two questions you proposed. I think both of them will work if you modified the termination condition in the iteration of search tree. It needs to be mentioned that MechRetro is fouced on single step prediction task while the pathway planning module in MechRetro is based on Retro*  algothim. The original repository can be found [here](https://github.com/binghong-ml/retro_star), which may help you to meet your customized needs. 
Best
