### ISSUE TITLE
some issues found when trying to process data

### ISSUE THREAD

**Issue by yz103** [wangyu-sd/MechRetro#8]
Hi,

Thank you very much for the great work. I tried to run the entry.py but found the following issues:

1. check_reactant is not provided in data_utils.py
2. mol is not provided in function map_id_alignment (data_utils.py)
![image](https://github.com/wangyu-sd/RetroExplainer/assets/47286622/a92b0b93-62e5-4c11-8ca9-c6c9c4fb4e66)

I would really appreciate your time. Thank you.

**Comment by Garhorne0813** [comment]
I had the same problems, too.

**Comment by newboy111** [comment]
I had the same problems, too.

**Comment by windy-BL** [comment]
The code is also missing key files.
FileNotFoundError: [Errno 2] No such file or directory: 'data/multi-step/retro_data/dataset/origin_dict.csv'

**Comment by wangyu-sd** [comment]
Apologies for the delayed response. This function has already been uploaded. Please don't hesitate to reach out if you have any questions.
